### PR TITLE
add docker-compose

### PR DESCRIPTION
**Pull request by dickymuliafiqri**

### CODE REVIEW

**Comment by BianSepang** [comment]
adding tutorial for docker-comppse is good,
but onecak module i think is not too useful

**Comment by dickymuliafiqri** [comment]
Yes, i know there's official apk of onecak.

But, why not ?
It's just for fun.
And i believe some people will using it.

Anyway, we can delete that module any time with easy.

But, at the end, the choices is on your hand.
😊

**Comment by BianSepang** [comment]
I'm just gonna merge docker-compose one
anyway, thx for PR

**Comment by dickymuliafiqri** [comment]
You're welcome

**Pull request merged**
